### ISSUE TITLE
Width for each item

### ISSUE THREAD

**Issue by cris-ms** [Nazeeh21/Chakra-UI-Carousel#11]
I add some buttons for carousel, but each button have a width and i can't change it.
How can i change it?

![Captura de tela de 2023-03-22 10-26-06](https://user-images.githubusercontent.com/104389276/226918903-44cad9cb-9187-4ee3-8720-758f988ecf92.png)

Code example:

`                    <Provider>
                        <Carousel gap={0}>
                        <Button />

                            {isAdminEmail ? (
                                <Button />
                            ) : (
                                <Button />
                            )}
                            <Button  />
                            <ChooseModelType />
                        </Carousel>
                    </Provider>`

**Comment by naz3eh** [comment]
You can just pass `width` prop to the button, just like we can in native Chakra components
