### ISSUE TITLE
Project completely broken

### ISSUE THREAD

**Issue by andreagiunti1** [Nazeeh21/Chakra-UI-Carousel#14]
Hi, 
This Carousel is completely broken, it has an infinite loop in which the width grows without an end.
How is this possible?

**Comment by naz3eh** [comment]
Sorry for the inconvenience. Can you please help to recover the error! as I tried it and it's working fine. You can have a look at the example [here](https://github.com/Nazeeh21/carousel-example/tree/f5f3d2886945fe83a2d4d3e695532ccc4e0b3f29) if that helps.
Or maybe you can watch the demo [here](https://carousel-example.vercel.app/)

**Comment by CheeseL0ver** [comment]
@Nazeeh21 I experienced this too. It seems to happen when certain components are used for additional positioning with a `Provider`, for example when I tried to follow your example that used the `Flex` element to set the buttons below the carousel it caused the width of the elements within the carousel is grow their width indefinitely. 

I am currently getting around this by not using additional organization components, however it definitely should be fixed before I could consider this for production. Happy to help debug if needed.

**Comment by naz3eh** [comment]
@CheeseL0ver sorry for the inconvenience. Can you please share a code sandbox link?

**Comment by CheeseL0ver** [comment]
I attempted to recreate the bug in a demo environment and I could not. My guess is the styles in the production app I am using are causing some odd behavior. I will post here again if I am ever able to find out more.

**Comment by naz3eh** [comment]
Sure thing! 👍

**Comment by naz3eh** [comment]
Meanwhile I am closing this, feel free to create again if you encounter any issue :)
