### ISSUE TITLE
Carousel tag children attribute

### ISSUE THREAD

**Issue by Rektovski** [Nazeeh21/Chakra-UI-Carousel#8]
Hi.

I'm trying to use chakra ui carousel component. I don't know what to do with children attribute.
When I try to copy paste this code into my project react says that carousel tag needs children attribute. I don't know what to insert in it.

<Box>
                <Provider>
                    <Carousel gap={50}   ****children={}******   >
                        
                    </Carousel>
                    <LeftButton
                        bgColor="red.500"
                        customIcon={<ArrowLeftIcon />}
                        textColor={"white.500"}
                    />
                    <RightButton bgColor="blue.500" customIcon={<ArrowRightIcon />} />
                </Provider>
            </Box>

**Comment by naz3eh** [comment]
hey @Rektovski, you have to pass some elements to the `Carousel` component. Have a look at the example below
```tsx 
<Provider>
            <Carousel gap={1}>
              <Box borderWidth={2} p={3} borderColor="white" borderRadius="md">
                Chakra UI Carousel
              </Box>
              <Box borderWidth={2} p={3} borderColor="white" borderRadius="md">
                Chakra UI Carousel
              </Box>
              <Box borderWidth={2} p={3} borderColor="white" borderRadius="md">
                Chakra UI Carousel
              </Box>
              <Box borderWidth={2} p={3} borderColor="white" borderRadius="md">
                Chakra UI Carousel
              </Box>
              <Box borderWidth={2} p={3} borderColor="white" borderRadius="md">
                Chakra UI Carousel
              </Box>
              <Box borderWidth={2} p={3} borderColor="white" borderRadius="md">
                Chakra UI Carousel
              </Box>
            </Carousel>
            <LeftButton />
            <RightButton />
          </Provider>
```

**Comment by naz3eh** [comment]
Closing this as I dont think a necessary fix is required
